[package]
name = "dsp_builder"
version = "0.1.0"
authors = ["탁동혁 <tdh8316@naver.com>"]
edition = "2018"
description = "DSPython linked object file builder"
license = "MIT"
repository = "https://github.com/tdh8316/dspython"

[dependencies]
